// Parity test cases: key sequences to run on a physical fx-991CE X and on the emulator.
// Test ids are positional (A01, A02, …) and key the recorded results: replace tests in place or append
// them at the end of a section, never insert or remove, so earlier results stay with their test.
// Key ids are the hardware keys (see src/calc/keymap.js). Every section starts from Initialize All
// (SHIFT 9 3 = AC) followed by the section's `start` keys; each test then begins with keys that bring
// the calculator to a known screen, so tests can be run one after another on the physical unit.
//   t(title, keys, { manual, core, note })
//     manual: the value the User's Guide prints for this operation (page given in the title)
//     core:   part of the shorter first pass

const t = (title, keys, opts = {}) => ({ title, keys, ...opts });

// SETUP shortcuts (each ends with AC so the setup menu is closed on any firmware behaviour)
const io = (n) => `SHIFT MENU 1 ${n} AC`; // 1 MathI/MathO, 2 MathI/DecimalO, 3 LineI/LineO, 4 LineI/DecimalO
const angle = (n) => `SHIFT MENU 2 ${n} AC`; // 1 Degree, 2 Radian, 3 Gradian
const fix = (d) => `SHIFT MENU 3 1 ${d} AC`;
const sci = (d) => `SHIFT MENU 3 2 ${d} AC`;
const norm = (d) => `SHIFT MENU 3 3 ${d} AC`;
const engSym = (on) => `SHIFT MENU 4 ${on ? 1 : 2} AC`;
const fracResult = (mixed) => `SHIFT MENU DOWN 1 ${mixed ? 1 : 2} AC`;
const complexForm = (polar) => `SHIFT MENU DOWN 2 ${polar ? 2 : 1} AC`;
const statFreq = (on) => `SHIFT MENU DOWN 3 ${on ? 1 : 2} AC`;
const showCellValue = () => 'SHIFT MENU DOWN 4 2 2 AC';
const eqComplex = (on) => `SHIFT MENU DOWN DOWN 1 ${on ? 1 : 2} AC`;
const table = (fg) => `SHIFT MENU DOWN DOWN 2 ${fg ? 2 : 1} AC`;
// fx-991CE X SETUP page 3: Equation/Func, Table, Digit Separator, MultiLine Font (no Decimal Mark)
const digitSep = (on) => `SHIFT MENU DOWN DOWN 3 ${on ? 1 : 2} AC`;

// ---------------------------------------------------------------- reusable data entry
const MAT_A = 'MENU 4 1 2 2 2 EQ 1 EQ 1 EQ 1 EQ AC'; // MatA = [2 1; 1 1]
const MAT_B = 'OPTN 1 2 2 2 2 EQ NEG 1 EQ NEG 1 EQ 2 EQ AC'; // MatB = [2 -1; -1 2]
const MAT_B23 = 'MENU 4 2 2 3 1 EQ 0 EQ NEG 1 EQ 0 EQ NEG 1 EQ 1 EQ AC'; // MatB = [1 0 -1; 0 -1 1]
const VCT_A = 'MENU 5 1 2 1 EQ 2 EQ AC'; // VctA = (1, 2)
const VCT_B = 'OPTN 1 2 2 3 EQ 4 EQ AC'; // VctB = (3, 4)
const FREQ_DATA = `${statFreq(1)} MENU 6 1 1 EQ 2 EQ 3 EQ 4 EQ 5 EQ DOWN RIGHT 1 EQ 2 EQ 3 EQ 2 EQ`; // Ex 2
const LOG_DATA = 'MENU 6 4 2 0 EQ 1 1 0 EQ 2 0 0 EQ 2 9 0 EQ DOWN RIGHT 3 1 5 0 EQ 7 3 1 0 EQ 8 8 0 0 EQ 9 3 1 0 EQ'; // Ex 3
const LIN_DATA = 'MENU 6 2 1 EQ 2 EQ 3 EQ DOWN RIGHT 2 EQ 4 EQ 7 EQ';
const QUAD_DATA = 'MENU 6 3 0 EQ 1 EQ 2 EQ 3 EQ DOWN RIGHT 1 EQ 3 EQ 7 EQ 1 3 EQ';
const SHEET = 'MENU 8 7 MUL 5 EQ 7 MUL 6 EQ ALPHA NEG 2 ADD 7 EQ'; // A1=7×5, A2=7×6, A3=A2+7
const SHEET_B1 = `${SHEET} UP UP UP RIGHT ALPHA CALC ALPHA NEG 1 ADD 7 EQ`; // B1: =A1+7
const TABLE_FG = 'MENU 9 AC ALPHA RP SQR ADD 1 FRAC 2 EQ AC ALPHA RP SQR SUB 1 FRAC 2 EQ NEG 1 EQ 1 EQ 0 DOT 5 EQ';

export const SECTIONS = [
  {
    id: 'A', title: 'Arithmetic, priority and entry', start: { text: 'Calculate mode, default setup', keys: '' },
    tests: [
      t('Functions, parentheses, implied × (p.8)', 'AC 4 MUL SIN 3 0 RP MUL LP 3 0 ADD 1 0 MUL 3 RP EQ', { manual: '120', core: true }),
      t('Implied × binds tighter than ÷ (p.8)', 'AC 6 DIV 2 LP 1 ADD 2 RP EQ', { manual: '1  (6÷(2(1+2)))', core: true }),
      t('Implied × before √ (p.8)', 'AC 2 DIV 2 SQRT 2 EQ', { manual: 'evaluated as 2÷(2√2)', core: true }),
      t('(−) sign versus x²', 'AC NEG 2 SQR EQ', { manual: '−4 (p.9 note)', core: true }),
      t('(−2)²', 'AC LP NEG 2 RP SQR EQ'),
      t('Mixed precedence', 'AC 1 ADD 2 MUL 3 SUB 4 DIV 5 EQ', { core: true }),
      t('Division gives a fraction; S⇔D', 'AC 7 DIV 2 EQ SD'),
      t('Exponent typed inside an exponent', 'AC 2 POW 3 POW 2 EQ', { core: true }),
      t('Leaving the exponent with ▶ first', 'AC 2 POW 3 RIGHT POW 2 EQ', { core: true }),
      t('×10ˣ with a negative exponent', 'AC 1 DOT 5 EXP NEG 3 EQ', { core: true }),
      t('… and S⇔D', 'AC 1 DOT 5 EXP NEG 3 EQ SD'),
      t('Large product', 'AC 1 2 3 4 5 6 7 8 9 MUL 9 8 7 6 5 4 3 2 1 EQ', { core: true }),
      t('Ten-digit integer', 'AC 9 9 9 9 9 9 9 9 9 9 EQ'),
      t('Exactly 10¹⁰', 'AC 1 EXP 1 0 EQ', { core: true }),
      t('0.009 in decimal (Norm 1 switches to ×10ⁿ)', 'AC 0 DOT 0 0 9 EQ SD', { core: true }),
      t('1÷3, then ×3', 'AC 1 DIV 3 EQ MUL 3 EQ'),
      t('Fraction + mixed fraction (p.10)', 'AC 2 FRAC 3 RIGHT ADD SHIFT FRAC 1 RIGHT 1 DOWN 2 EQ', { manual: '13/6', core: true }),
      t('… then a b/c ⇔ d/c', 'AC 2 FRAC 3 RIGHT ADD SHIFT FRAC 1 RIGHT 1 DOWN 2 EQ SHIFT SD'),
      t('0.1 + 0.2', 'AC 0 DOT 1 ADD 0 DOT 2 EQ', { core: true }),
      t('Fraction too long for the display', 'AC 1 DIV 1 2 3 4 5 6 7 8 9 EQ', { core: true }),
      t('Longest fraction that fits (10 digits)', 'AC 1 DIV 1 2 3 4 5 6 7 8 EQ'),
      t('2⁴⁰', 'AC 2 POW 4 0 EQ'),
      t('69!', 'AC 6 9 SHIFT INV EQ', { core: true }),
      t('70! is out of range (p.40)', 'AC 7 0 SHIFT INV EQ', { manual: 'Math ERROR' }),
      t('Division by zero', 'AC 1 DIV 0 EQ', { manual: 'Math ERROR', core: true }),
      t('Syntax error', 'AC 1 ADD MUL 2 EQ', { manual: 'Syntax ERROR', core: true }),
      t('Overflow: 10⁹⁹×10', 'AC 1 0 POW 9 9 RIGHT MUL 1 0 EQ', { manual: 'Math ERROR' }),
      t('Underflow: 10⁻⁹⁹÷10', 'AC 1 0 POW NEG 9 9 RIGHT DIV 1 0 EQ'),
      t('Ans carries into the next calculation (p.13)', 'AC 1 4 MUL 1 3 EQ DIV 7 EQ', { manual: '26', core: true }),
      t('Ans key (p.13)', 'AC 1 2 3 ADD 4 5 6 EQ 7 8 9 SUB ANS EQ', { manual: '210' }),
      t('Replay and edit (p.12)', 'AC 4 MUL 3 ADD 2 EQ LEFT DEL DEL SUB 7 EQ', { manual: '5', core: true }),
      t('History ▲ (p.12)', 'AC 2 ADD 2 EQ 3 ADD 3 EQ UP', { manual: '4 (2+2 shown)', core: true }),
      t('Multi-statement, first result (p.11)', 'AC 3 ADD 3 ALPHA INT 3 MUL 3 EQ', { manual: '6', core: true }),
      t('Multi-statement, second result (p.11)', 'AC 3 ADD 3 ALPHA INT 3 MUL 3 EQ EQ', { manual: '9' }),
      t('Percent (p.11)', 'AC 1 5 0 MUL 2 0 SHIFT ANS EQ', { manual: '30', core: true }),
      t('What % of 880 is 660 (p.11)', 'AC 6 6 0 DIV 8 8 0 SHIFT ANS EQ', { manual: '75' }),
      t('Discount 3500 by 25% (p.11)', 'AC 3 5 0 0 SUB 3 5 0 0 MUL 2 5 SHIFT ANS EQ', { manual: '2625' }),
      t('Repeated = re-runs Ans+1', 'AC 5 EQ ANS ADD 1 EQ EQ EQ'),
      t('DEL deletes left of the cursor', 'AC 1 2 3 LEFT LEFT DEL 9 EQ'),
      t('INS makes 7/6 the √ argument (p.10)', 'AC 1 ADD 7 FRAC 6 LEFT LEFT LEFT LEFT SHIFT DEL SQRT EQ', { core: true }),
      t('UNDO restores a deleted digit (p.9)', 'AC 1 2 3 DEL ALPHA DEL EQ'),
      t('1÷2π (implied × with π)', 'AC 1 DIV 2 SHIFT EXP EQ', { core: true }),
    ],
  },
  {
    id: 'B', title: 'Fractions, √ forms and π forms (MathI/MathO)', start: { text: 'Calculate mode, default setup', keys: '' },
    tests: [
      t('√8 simplifies', 'AC SQRT 8 EQ', { core: true }),
      t('√2 × 3 (p.15)', 'AC SQRT 2 RIGHT MUL 3 EQ', { manual: '3√2', core: true }),
      t('(√2+2)×√3 (p.10)', 'AC LP SQRT 2 RIGHT ADD 2 RP MUL SQRT 3 EQ', { manual: '√6+2√3', core: true }),
      t('Two-term order: 10√2+15×3√3', 'AC 1 0 SQRT 2 RIGHT ADD 1 5 MUL 3 SQRT 3 EQ', { manual: '45√3+10√2 (fx-991ES PLUS guide)', core: true }),
      t('Outside the √ range: 99√999', 'AC 9 9 SQRT 9 9 9 EQ', { manual: '3129.089165 (fx-991ES PLUS guide)', core: true }),
      t('1÷√2', 'AC 1 DIV SQRT 2 EQ', { core: true }),
      t('√(1/2)', 'AC SQRT FRAC 1 DOWN 2 EQ'),
      t('(1+√2)²', 'AC LP 1 ADD SQRT 2 RIGHT RP SQR EQ', { core: true }),
      t('1÷(1+√2)', 'AC 1 DIV LP 1 ADD SQRT 2 RIGHT RP EQ', { core: true }),
      t('Three radicals', 'AC SQRT 2 RIGHT ADD SQRT 3 RIGHT ADD SQRT 5 EQ', { core: true }),
      t('√12345', 'AC SQRT 1 2 3 4 5 EQ'),
      t('(2+√3)(2−√3)', 'AC LP 2 ADD SQRT 3 RIGHT RP LP 2 SUB SQRT 3 RIGHT RP EQ'),
      t('−1÷√2', 'AC NEG 1 DIV SQRT 2 EQ'),
      t('√2 in a fraction template', 'AC FRAC SQRT 2 RIGHT DOWN 2 EQ'),
      t('√3 ÷ 2', 'AC SQRT 3 RIGHT DIV 2 EQ'),
      t('√ form, then S⇔D', 'AC SQRT 8 EQ SD'),
      t('π÷6 (p.10)', 'AC SHIFT EXP DIV 6 EQ', { manual: '1/6 π', core: true }),
      t('π÷6, then S⇔D (p.10)', 'AC SHIFT EXP DIV 6 EQ SD', { manual: '0.5235987756' }),
      t('2π + π/2', 'AC 2 SHIFT EXP ADD SHIFT EXP DIV 2 EQ', { core: true }),
      t('π + 1', 'AC SHIFT EXP ADD 1 EQ', { core: true }),
      t('π²', 'AC SHIFT EXP SQR EQ'),
      t('1000000π (π form limit |x| < 10⁶, p.41)', 'AC 1 0 0 0 0 0 0 SHIFT EXP EQ'),
      t('1.5 entered as a decimal', 'AC 1 DOT 5 EQ', { core: true }),
      t('√(−4) in Calculate mode', 'AC SQRT NEG 4 EQ', { core: true }),
    ],
  },
  {
    id: 'C', title: 'Setup: input/output and number formats', start: { text: 'Calculate mode; each test sets what it needs', keys: '' },
    tests: [
      t('LineI/LineO: 1÷3', `AC ${io(3)} 1 DIV 3 EQ`, { core: true }),
      t('LineI/LineO fraction input (p.10)', `AC ${io(3)} 2 FRAC 3 ADD 1 FRAC 1 FRAC 2 EQ`, { manual: '13⌟6', core: true }),
      t('LineI/LineO: √2×3 (p.15)', `AC ${io(3)} SQRT 2 RP MUL 3 EQ`, { manual: '4.242640687' }),
      t('LineI/LineO: fraction mixed with a decimal (p.11)', `AC ${io(3)} 1 FRAC 3 ADD 0 DOT 5 EQ`, { manual: 'decimal result' }),
      t('LineI/DecimalO', `AC ${io(4)} 1 FRAC 2 ADD 1 FRAC 3 EQ`),
      t('LineI/DecimalO, then S⇔D', `AC ${io(4)} 1 FRAC 2 ADD 1 FRAC 3 EQ SD`),
      t('MathI/DecimalO (p.10)', `AC ${io(2)} LP SQRT 2 RIGHT ADD 2 RP MUL SQRT 3 EQ`, { manual: '5.913591358', core: true }),
      t('MathI/DecimalO, then S⇔D (p.10)', `AC ${io(2)} LP SQRT 2 RIGHT ADD 2 RP MUL SQRT 3 EQ SD`, { manual: '√6+2√3' }),
      t('Fix 3 with ≈ (p.6)', `AC ${io(1)} ${fix(3)} 1 0 0 DIV 7 SHIFT EQ`, { manual: '14.286', core: true }),
      t('Fix 3, MathO fraction result', `AC ${fix(3)} 1 0 0 DIV 7 EQ`, { core: true }),
      t('Sci 5 (p.7)', `AC ${sci(5)} 1 DIV 7 SHIFT EQ`, { manual: '1.4286×10⁻¹', core: true }),
      t('Sci 0 (10 digits)', `AC ${sci(0)} 1 DIV 7 SHIFT EQ`),
      t('Norm 1 (p.7)', `AC ${norm(1)} 1 DIV 2 0 0 SHIFT EQ`, { manual: '5×10⁻³', core: true }),
      t('Norm 2 (p.7)', `AC ${norm(2)} 1 DIV 2 0 0 SHIFT EQ`, { manual: '0.005', core: true }),
      t('Norm 2 with a small value', `AC ${norm(2)} 1 DIV 3 0 0 0 SHIFT EQ`, { core: true }),
      t('Fix 0 rounds 2.5', `AC ${fix(0)} 5 DIV 2 SHIFT EQ`),
      t('Fix 2 with a large value', `AC ${fix(2)} 1 EXP 1 2 EQ`),
      t('Fix 3: 10÷3×3 (p.16)', `AC ${io(2)} ${fix(3)} 1 0 DIV 3 MUL 3 EQ`, { manual: '10.000', core: true }),
      t('Fix 3: Rnd(10÷3)×3 (p.16)', `AC ${io(2)} ${fix(3)} SHIFT 0 1 0 DIV 3 RP MUL 3 EQ`, { manual: '9.999', core: true }),
      t('Engineer Symbol: 999k+25k (p.12)', `AC ${io(1)} ${norm(1)} ${engSym(1)} 9 9 9 OPTN 3 6 ADD 2 5 OPTN 3 6 EQ`, { manual: '1.024M', core: true }),
      t('… then ENG (p.12)', `AC ${engSym(1)} 9 9 9 OPTN 3 6 ADD 2 5 OPTN 3 6 EQ ENG`, { manual: '1024k' }),
      t('Engineer Symbol: 1÷2', `AC ${engSym(1)} 1 DIV 2 SHIFT EQ`),
      t('Fraction Result ab/c', `AC ${engSym(0)} ${fracResult(1)} 7 DIV 3 EQ`, { core: true }),
      t('Decimal comma', `AC ${fracResult(0)} ${digitSep(0)} 1 DIV 4 SHIFT EQ`),
      t('Digit Separator: On', `AC ${digitSep(1)} 1 2 3 4 5 6 7 MUL 8 EQ`),
      t('SETUP menu, page 1', `AC ${digitSep(0)} SHIFT MENU`, { core: true }),
      t('SETUP menu, page 2', 'AC SHIFT MENU DOWN'),
      t('SETUP menu, page 3', 'AC SHIFT MENU DOWN DOWN'),
      t('SETUP menu, page 4', 'AC SHIFT MENU DOWN DOWN DOWN'),
      t('Input/Output submenu', 'AC SHIFT MENU 1'),
      t('Number Format submenu', 'AC SHIFT MENU 3'),
      t('Language list (fx-991CE X)', 'AC SHIFT MENU DOWN DOWN DOWN 1'),
      t('MultiLine Font submenu', 'AC SHIFT MENU DOWN DOWN 4'),
    ],
  },
  {
    id: 'D', title: 'ENG, S⇔D, FACT and sexagesimal', start: { text: 'Calculate mode, default setup', keys: '' },
    tests: [
      t('ENG (p.11)', 'AC 1 2 3 4 EQ ENG', { manual: '1.234×10³', core: true }),
      t('ENG twice (p.11)', 'AC 1 2 3 4 EQ ENG ENG', { manual: '1234×10⁰' }),
      t('ENG twice, then ← (p.11)', 'AC 1 2 3 4 EQ ENG ENG SHIFT ENG', { manual: '1.234×10³' }),
      t('ENG twice, then ← twice (p.11)', 'AC 1 2 3 4 EQ ENG ENG SHIFT ENG SHIFT ENG', { manual: '0.001234×10⁶', core: true }),
      t('ENG on a small value', 'AC 0 DOT 0 0 0 1 2 3 EQ ENG'),
      t('FACT (p.12)', 'AC 1 0 1 4 EQ SHIFT DMS', { manual: '2×3×13²', core: true }),
      t('FACT with two 4-digit primes (p.12 rule)', 'AC 1 0 0 9 MUL 1 0 1 3 EQ SHIFT DMS', { manual: 'unfactored part in parentheses', core: true }),
      t('FACT with one 4-digit prime', 'AC 6 1 2 6 EQ SHIFT DMS'),
      t('FACT of a fraction', 'AC 1 DIV 2 EQ SHIFT DMS'),
      t('FACT pressed again restores (p.12)', 'AC 1 0 1 4 EQ SHIFT DMS SHIFT DMS', { manual: '1014' }),
      t('Sexagesimal addition (p.11)', 'AC 2 DMS 2 0 DMS 3 0 DMS ADD 0 DMS 9 DMS 3 0 DMS EQ', { manual: '2°30′0″', core: true }),
      t('Sexagesimal → decimal (p.11)', 'AC 2 DMS 2 0 DMS 3 0 DMS ADD 0 DMS 9 DMS 3 0 DMS EQ DMS', { manual: '2.5' }),
      t('Decimal → sexagesimal', 'AC 2 DOT 2 5 8 EQ DMS', { core: true }),
      t('Sexagesimal × 3', 'AC 1 DMS 3 0 DMS MUL 3 EQ'),
      t('S⇔D on 0.75', 'AC 0 DOT 7 5 EQ SD'),
      t('a b/c ⇔ d/c on 11/4', 'AC 1 1 DIV 4 EQ SHIFT SD'),
    ],
  },
  {
    id: 'E', title: 'Functions (Degree)', start: { text: 'Calculate mode, default setup (Degree)', keys: '' },
    tests: [
      t('sin 30° (p.14)', 'AC SIN 3 0 RP EQ', { manual: '1/2', core: true }),
      t('cos 60°', 'AC COS 6 0 RP EQ'),
      t('tan 45°', 'AC TAN 4 5 RP EQ'),
      t('sin 60°', 'AC SIN 6 0 RP EQ', { core: true }),
      t('tan 30°', 'AC TAN 3 0 RP EQ', { core: true }),
      t('tan 60°', 'AC TAN 6 0 RP EQ'),
      t('sin 45°', 'AC SIN 4 5 RP EQ'),
      t('sin 15°', 'AC SIN 1 5 RP EQ', { core: true }),
      t('sin 18°', 'AC SIN 1 8 RP EQ', { core: true }),
      t('cos 36°', 'AC COS 3 6 RP EQ'),
      t('sin 36°', 'AC SIN 3 6 RP EQ', { core: true }),
      t('tan 15°', 'AC TAN 1 5 RP EQ', { core: true }),
      t('tan 75°', 'AC TAN 7 5 RP EQ'),
      t('sin 225°', 'AC SIN 2 2 5 RP EQ'),
      t('cos 120°', 'AC COS 1 2 0 RP EQ'),
      t('sin 180°', 'AC SIN 1 8 0 RP EQ', { core: true }),
      t('sin 1°', 'AC SIN 1 RP EQ', { core: true }),
      t('tan 90° (p.40)', 'AC TAN 9 0 RP EQ', { manual: 'Math ERROR', core: true }),
      t('sin(9×10⁹)° (input range, p.40)', 'AC SIN 9 MUL 1 0 POW 9 RIGHT RP EQ', { manual: 'Math ERROR' }),
      t('sin⁻¹(1/2)', 'AC SHIFT SIN 1 FRAC 2 RIGHT RP EQ', { core: true }),
      t('sin⁻¹ 0.3', 'AC SHIFT SIN 0 DOT 3 RP EQ'),
      t('cos⁻¹(−1)', 'AC SHIFT COS NEG 1 RP EQ'),
      t('tan⁻¹ √3', 'AC SHIFT TAN SQRT 3 RIGHT RP EQ', { core: true }),
      t('sin⁻¹ 1.1', 'AC SHIFT SIN 1 DOT 1 RP EQ', { manual: 'Math ERROR' }),
      t('(π/2)ʳ in Degree (p.14)', 'AC LP SHIFT EXP DIV 2 RP OPTN 2 2 EQ', { manual: '90', core: true }),
      t('sinh 1', 'AC OPTN 1 1 1 RP EQ', { core: true }),
      t('cosh⁻¹ 2', 'AC OPTN 1 5 2 RP EQ'),
      t('tanh⁻¹ 1 (p.41)', 'AC OPTN 1 6 1 RP EQ', { manual: 'Math ERROR' }),
      t('log 1000 (p.14)', 'AC SHIFT NEG 1 0 0 0 RP EQ', { manual: '3', core: true }),
      t('log(2,16) (p.14)', 'AC SHIFT NEG 2 SHIFT RP 1 6 RP EQ', { manual: '4' }),
      t('log▫▫ template (p.14)', 'AC LOG 2 RIGHT 1 6 EQ', { manual: '4', core: true }),
      t('log₄ 2', 'AC LOG 4 RIGHT 2 EQ', { core: true }),
      t('log 2', 'AC SHIFT NEG 2 RP EQ'),
      t('ln 90 (p.14)', 'AC LN 9 0 RP EQ', { manual: '4.49980967', core: true }),
      t('e⁵×2 (p.14)', 'AC SHIFT LN 5 RIGHT MUL 2 EQ', { manual: '296.8263182', core: true }),
      t('10^0.5', 'AC SHIFT LOG 0 DOT 5 EQ', { core: true }),
      t('ln 0', 'AC LN 0 RP EQ', { manual: 'Math ERROR' }),
      t('e²³¹ (p.41)', 'AC SHIFT LN 2 3 1 EQ', { manual: 'Math ERROR' }),
      t('2^(1/2)', 'AC 2 POW 1 FRAC 2 EQ', { core: true }),
      t('(−8)^(1/3) (p.41)', 'AC LP NEG 8 RP POW 1 FRAC 3 EQ', { core: true }),
      t('(−8)^(1/2)', 'AC LP NEG 8 RP POW 1 FRAC 2 EQ', { manual: 'Math ERROR' }),
      t('∛27', 'AC SHIFT SQRT 2 7 EQ'),
      t('⁵√32 (p.14)', 'AC SHIFT POW 5 RIGHT 3 2 EQ', { manual: '2' }),
      t('4⁻¹', 'AC 4 INV EQ'),
      t('(5²)³ (p.14)', 'AC LP 5 SQR RP SHIFT SQR EQ', { manual: '15625' }),
      t('Abs (p.16)', 'AC SHIFT LP 2 SUB 7 RIGHT MUL 2 EQ', { manual: '10', core: true }),
      t('10P4 (p.16)', 'AC 1 0 SHIFT MUL 4 EQ', { manual: '5040' }),
      t('10C4 (p.16)', 'AC 1 0 SHIFT DIV 4 EQ', { manual: '210' }),
      t('200C100 (input range, p.41)', 'AC 2 0 0 SHIFT DIV 1 0 0 EQ', { core: true }),
      t('Pol(√2, √2) (p.16)', 'AC SHIFT ADD SQRT 2 RIGHT SHIFT RP SQRT 2 RIGHT RP EQ', { manual: 'r=2, θ=45', core: true }),
      t('Rec(√2, 45) (p.16)', 'AC SHIFT SUB SQRT 2 RIGHT SHIFT RP 4 5 RP EQ', { manual: 'x=1, y=1', core: true }),
      t('Pol(−1, 0)', 'AC SHIFT ADD NEG 1 SHIFT RP 0 RP EQ'),
      t('0⁰', 'AC 0 POW 0 EQ', { core: true }),
      t('2⁻¹', 'AC 2 POW NEG 1 EQ'),
      t('sin²30°', 'AC SIN 3 0 RP SQR EQ'),
      t('sin 30 + 15 without ")" (FAQ p.43)', 'AC SIN 3 0 ADD 1 5 EQ', { manual: 'sin 45 is calculated', core: true }),
      t('(sin 30) + 15 (FAQ p.43)', 'AC SIN 3 0 RP ADD 1 5 EQ', { manual: '15.5 (31/2)' }),
    ],
  },
  {
    id: 'F', title: 'Radian and Gradian', start: { text: 'SETUP → Angle Unit → Radian', keys: angle(2) },
    tests: [
      t('sin(π/6)', 'AC SIN SHIFT EXP DIV 6 RP EQ', { core: true }),
      t('sin π', 'AC SIN SHIFT EXP RP EQ', { core: true }),
      t('cos(π/2)', 'AC COS SHIFT EXP DIV 2 RP EQ'),
      t('tan(π/2) (p.40)', 'AC TAN SHIFT EXP DIV 2 RP EQ', { manual: 'Math ERROR', core: true }),
      t('sin 1', 'AC SIN 1 RP EQ'),
      t('sin⁻¹(1/2) in π form', 'AC SHIFT SIN 1 FRAC 2 RIGHT RP EQ', { core: true }),
      t('cos⁻¹(−1)', 'AC SHIFT COS NEG 1 RP EQ'),
      t('tan⁻¹ 1', 'AC SHIFT TAN 1 RP EQ', { core: true }),
      t('90° in radians', 'AC 9 0 OPTN 2 1 EQ'),
      t('sin of a typed 15-digit π', 'AC SIN 3 DOT 1 4 1 5 9 2 6 5 3 5 8 9 7 9 RP EQ', { core: true }),
      t('d/dx sin x at π/2 (p.15)', 'AC SHIFT INT SIN ALPHA RP RP RIGHT SHIFT EXP DIV 2 EQ', { manual: '0', core: true }),
      t('∫₀^π sin x dx', 'AC INT SIN ALPHA RP RP RIGHT 0 RIGHT SHIFT EXP EQ', { core: true }),
      t('Pol(1, 1) in Radian', `AC ${angle(2)} SHIFT ADD 1 SHIFT RP 1 RP EQ`), // sets Radian itself so it can be rerun alone
      t('Gradian: sin 50', `AC ${angle(3)} SIN 5 0 RP EQ`, { core: true }),
      t('Gradian: cos 100', `AC ${angle(3)} COS 1 0 0 RP EQ`),
      t('Gradian: 90° in grads', `AC ${angle(3)} 9 0 OPTN 2 1 EQ`),
    ],
  },
  {
    id: 'G', title: 'Integration, derivatives and Σ', start: { text: 'Calculate mode, default setup', keys: '' },
    tests: [
      t('∫₁ᵉ ln x dx (p.15)', 'AC INT LN ALPHA RP RP RIGHT 1 RIGHT ALPHA EXP EQ', { manual: '1', core: true }),
      t('∫₀¹ x² dx', 'AC INT ALPHA RP SQR RIGHT 0 RIGHT 1 EQ', { core: true }),
      t('∫₀¹ 4/(1+x²) dx', 'AC INT 4 FRAC 1 ADD ALPHA RP SQR RIGHT RIGHT 0 RIGHT 1 EQ', { core: true }),
      t('∫₁² 1/x dx', 'AC INT 1 FRAC ALPHA RP RIGHT RIGHT 1 RIGHT 2 EQ'),
      t('∫ with reversed limits', 'AC INT ALPHA RP RIGHT 1 RIGHT 0 EQ'),
      t('d/dx x³ at x=2', 'AC SHIFT INT ALPHA RP SHIFT SQR RIGHT 2 EQ', { core: true }),
      t('d/dx ln x at x=3', 'AC SHIFT INT LN ALPHA RP RP RIGHT 3 EQ'),
      t('d/dx |x| at x=0 (not differentiable)', 'AC SHIFT INT SHIFT LP ALPHA RP RIGHT RIGHT 0 EQ', { core: true }),
      t('Σ(x+1), x=1…5 (p.15)', 'AC SHIFT X ALPHA RP ADD 1 RIGHT 1 RIGHT 5 EQ', { manual: '20', core: true }),
      t('Σ x², x=1…10', 'AC SHIFT X ALPHA RP SQR RIGHT 1 RIGHT 1 0 EQ'),
      t('Σ 1/x², x=1…100', 'AC SHIFT X 1 FRAC ALPHA RP SQR RIGHT RIGHT 1 RIGHT 1 0 0 EQ', { core: true }),
      t('Σ with a non-integer limit (p.15)', 'AC SHIFT X ALPHA RP RIGHT 1 DOT 5 RIGHT 3 EQ'),
      t('∫ in LineI/LineO with tol', `AC ${io(3)} INT ALPHA RP SQR SHIFT RP 0 SHIFT RP 3 SHIFT RP 1 EXP NEG 8 RP EQ`),
    ],
  },
  {
    id: 'H', title: 'Memory, CALC and SOLVE', start: { text: 'Calculate mode, default setup', keys: '' },
    tests: [
      t('STO to A (p.13)', 'AC 3 ADD 5 STO NEG', { manual: '8', core: true }),
      t('Using A (p.13)', 'AC 3 ADD 5 STO NEG ALPHA NEG MUL 1 0 EQ', { manual: '80' }),
      t('RECALL screen (p.13)', 'AC 3 ADD 5 STO NEG SHIFT STO', { core: true }),
      t('RECALL inserts A (p.13)', 'AC 3 ADD 5 STO NEG SHIFT STO NEG EQ', { manual: '8' }),
      t('Clear A (p.13)', 'AC 0 STO NEG', { manual: '0' }),
      t('M+ and M− (p.13)', 'AC 0 STO MPLUS 1 0 MUL 5 MPLUS 1 0 ADD 5 SHIFT MPLUS SHIFT STO MPLUS EQ', { manual: '35', core: true }),
      t('STO to x with the x key', 'AC 2 STO X X SQR ADD 1 EQ'),
      t('CALC (p.18)', 'AC 3 ALPHA NEG ADD ALPHA DMS CALC 5 EQ 1 0 EQ', { manual: '25', core: true }),
      t('CALC prompt screen (p.18)', 'AC 3 ALPHA NEG ADD ALPHA DMS CALC', { manual: 'A=0 highlighted' }),
      t('CALC with y = x²+x+3, x=2 (p.18)', 'AC ALPHA SD ALPHA CALC ALPHA RP SQR ADD ALPHA RP ADD 3 CALC 2 EQ'),
      t('SOLVE x²+B=0, B=−2 (p.19)', 'AC ALPHA RP SQR ADD ALPHA DMS ALPHA CALC 0 SHIFT CALC 1 EQ NEG 2 EQ UP EQ', { manual: 'x=1.414213562, L−R=0', core: true }),
      t('SOLVE x³−2x−5 from 2', 'AC ALPHA RP SHIFT SQR SUB 2 ALPHA RP SUB 5 SHIFT CALC 2 EQ EQ', { core: true }),
      t('SOLVE x²−4 (no "=") from 1', 'AC ALPHA RP SQR SUB 4 SHIFT CALC 1 EQ EQ'),
      t('SOLVE x²−4 from −1', 'AC ALPHA RP SQR SUB 4 SHIFT CALC NEG 1 EQ EQ', { core: true }),
      t('SOLVE sin x = 0.5 from 10', 'AC SIN ALPHA RP RP ALPHA CALC 0 DOT 5 SHIFT CALC 1 0 EQ EQ', { core: true }),
      t('SOLVE with no variable (p.38)', 'AC 2 ADD 3 SHIFT CALC', { manual: 'Variable ERROR' }),
      t('SOLVE x²+1=0 (no real root)', 'AC ALPHA RP SQR ADD 1 SHIFT CALC 1 EQ EQ', { core: true }),
      t('SOLVE prompt screen (after Memory reset)', 'AC SHIFT 9 2 EQ AC ALPHA RP SQR SUB 4 SHIFT CALC'), // x=0 regardless of earlier tests
    ],
  },
  {
    id: 'I', title: 'Complex mode', start: { text: 'MENU → 2 (Complex)', keys: 'MENU 2' },
    tests: [
      t('(1+i)⁴+(1−i)² (p.18)', 'AC LP 1 ADD ENG RP POW 4 RIGHT ADD LP 1 SUB ENG RP SQR EQ', { manual: '−4−2i', core: true }),
      t('2∠45 (p.18)', 'AC 2 SHIFT ENG 4 5 EQ', { manual: '√2+√2i', core: true }),
      t('▸r∠θ (p.18)', 'AC SQRT 2 RIGHT ADD SQRT 2 RIGHT ENG OPTN DOWN 1 EQ', { manual: '2∠45', core: true }),
      t('▸a+bi (p.18)', 'AC 2 SHIFT ENG 4 5 OPTN DOWN 2 EQ', { manual: '√2+√2i' }),
      t('Conjugate (p.18)', 'AC OPTN 2 2 ADD 3 ENG RP EQ', { manual: '2−3i' }),
      t('Abs (p.18)', 'AC SHIFT LP 1 ADD ENG EQ', { manual: '√2' }),
      t('Argument (p.18)', 'AC OPTN 1 1 ADD ENG RP EQ', { manual: '45' }),
      t('Real part (p.18)', 'AC OPTN 3 2 ADD 3 ENG RP EQ', { manual: '2' }),
      t('Imaginary part (p.18)', 'AC OPTN 4 2 ADD 3 ENG RP EQ', { manual: '3' }),
      t('(3+4i)÷(1−2i)', 'AC LP 3 ADD 4 ENG RP DIV LP 1 SUB 2 ENG RP EQ', { core: true }),
      t('i²', 'AC ENG SQR EQ'),
      t('√(−4)', 'AC SQRT NEG 4 EQ', { core: true }),
      t('1÷i', 'AC 1 DIV ENG EQ'),
      t('(1+i)^0.5', 'AC LP 1 ADD ENG RP POW 0 DOT 5 EQ', { core: true }),
      t('sin i', 'AC SIN ENG RP EQ', { core: true }),
      t('Complex setting r∠θ (p.18)', `AC ${complexForm(1)} SQRT 2 RIGHT ADD SQRT 2 RIGHT ENG EQ`, { manual: '2∠45', core: true }),
      t('r∠θ of −2', `AC ${complexForm(1)} NEG 2 EQ`),
      t('OPTN menu, page 1', `AC ${complexForm(0)} OPTN`),
    ],
  },
  {
    id: 'J', title: 'Base-N mode', start: { text: 'MENU → 3 (Base-N)', keys: 'MENU 3' },
    tests: [
      t('BIN 11+1 (p.23)', 'AC LOG 1 1 ADD 1 EQ', { core: true }),
      t('d10+h10+b10+o10 (p.23)', 'AC SQR OPTN DOWN 1 1 0 ADD OPTN DOWN 2 1 0 ADD OPTN DOWN 3 1 0 ADD OPTN DOWN 4 1 0 EQ', { manual: '36', core: true }),
      t('15×37 → HEX (p.24)', 'AC SQR 1 5 MUL 3 7 EQ POW', { manual: '0000022B', core: true }),
      t('1010 and 1100 (p.24)', 'AC LOG 1 0 1 0 OPTN 3 1 1 0 0 EQ', { manual: '…0000 1000' }),
      t('Not(1010) (p.24)', 'AC LOG OPTN 2 1 0 1 0 RP EQ', { manual: '…1111 0101', core: true }),
      t('1010 or 1100', 'AC LOG 1 0 1 0 OPTN 4 1 1 0 0 EQ'),
      t('1010 xor 1100', 'AC LOG 1 0 1 0 OPTN 5 1 1 0 0 EQ'),
      t('1010 xnor 1100', 'AC LOG 1 0 1 0 OPTN 6 1 1 0 0 EQ'),
      t('Neg(1) in HEX', 'AC POW OPTN 1 1 RP EQ', { core: true }),
      t('HEX FF+1', 'AC POW TAN TAN ADD 1 EQ'),
      t('DEC 7÷2 truncates (p.23)', 'AC SQR 7 DIV 2 EQ', { core: true }),
      t('DEC overflow', 'AC SQR 2 1 4 7 4 8 3 6 4 7 ADD 1 EQ', { core: true }),
      t('Neg(1) shown in BIN', 'AC SQR OPTN 1 1 RP EQ LOG'),
      t('OCT 777 → DEC', 'AC LN 7 7 7 EQ SQR'),
      t('Decimal point in Base-N (p.23)', 'AC SQR 1 DOT 5 EQ'),
      t('OPTN menu', 'AC OPTN'),
    ],
  },
  {
    id: 'K', title: 'Matrix mode', start: { text: 'MENU → 4 (Matrix); each test re-enters the mode', keys: '' },
    tests: [
      t('Matrix editor for MatA (p.25)', 'MENU 4 1 2 2 2 EQ 1 EQ 1 EQ 1 EQ', { core: true }),
      t('MatA×MatB (p.26)', `${MAT_A} ${MAT_B} OPTN 3 MUL OPTN 4 EQ`, { manual: '[3 0; 1 1]', core: true }),
      t('Det(MatA) (p.26)', `${MAT_A} OPTN DOWN 2 OPTN 3 RP EQ`, { manual: '1', core: true }),
      t('Identity(2)+MatA (p.26)', `${MAT_A} OPTN DOWN 4 2 RP ADD OPTN 3 EQ`, { manual: '[3 1; 1 2]' }),
      t('MatA⁻¹ (p.27)', `${MAT_A} OPTN 3 INV EQ`, { manual: '[1 −1; −1 2]', core: true }),
      t('MatA² (p.27)', `${MAT_A} OPTN 3 SQR EQ`, { manual: '[5 3; 3 2]' }),
      t('MatA³ (p.27)', `${MAT_A} OPTN 3 SHIFT SQR EQ`, { manual: '[13 8; 8 5]' }),
      t('Trn(MatB), 2×3 (p.27)', `${MAT_B23} OPTN DOWN 3 OPTN 4 RP EQ`, { manual: '[1 0; 0 −1; −1 1]' }),
      t('Abs(MatB) (p.27)', `${MAT_B23} SHIFT LP OPTN 4 RP EQ`, { manual: '[1 0 1; 0 1 1]' }),
      t('3×3 determinant', 'MENU 4 1 3 3 2 EQ 1 EQ 0 EQ 1 EQ 3 EQ 1 EQ 0 EQ 1 EQ 4 EQ AC OPTN DOWN 2 OPTN 3 RP EQ', { core: true }),
      t('Inverse of a singular matrix', 'MENU 4 1 2 2 1 EQ 2 EQ 2 EQ 4 EQ AC OPTN 3 INV EQ', { manual: 'Math ERROR' }),
      t('Adding 2×2 and 2×3 (p.38)', 'MENU 4 1 2 2 1 EQ 2 EQ 3 EQ 4 EQ AC OPTN 1 2 2 3 1 EQ 2 EQ 3 EQ 4 EQ 5 EQ 6 EQ AC OPTN 3 ADD OPTN 4 EQ', { manual: 'Dimension ERROR' }),
      t('Inverse with fractions', 'MENU 4 1 2 2 2 EQ 1 EQ 1 EQ 3 EQ AC OPTN 3 INV EQ', { core: true }),
      t('3×MatA', `${MAT_A} 3 OPTN 3 EQ`),
      t('OPTN menu, page 1', `${MAT_A} OPTN`),
      t('OPTN menu, page 2', `${MAT_A} OPTN DOWN`),
    ],
  },
  {
    id: 'L', title: 'Vector mode', start: { text: 'MENU → 5 (Vector); each test re-enters the mode', keys: '' },
    tests: [
      t('Vector editor for VctA (p.28)', 'MENU 5 1 2 1 EQ 2 EQ', { core: true }),
      t('VctA+VctB (p.28)', `${VCT_A} ${VCT_B} OPTN 3 ADD OPTN 4 EQ`, { manual: '(4, 6)' }),
      t('VctA•VctB (p.29)', `${VCT_A} ${VCT_B} OPTN 3 OPTN DOWN 2 OPTN 4 EQ`, { manual: '11', core: true }),
      t('VctA×VctB (p.29)', `${VCT_A} ${VCT_B} OPTN 3 MUL OPTN 4 EQ`, { manual: '(0, 0, −2)', core: true }),
      t('Abs(VctC) (p.29)', 'MENU 5 3 3 2 EQ NEG 1 EQ 2 EQ AC SHIFT LP OPTN 5 RP EQ', { manual: '3' }),
      t('UnitV(VctB) (p.29)', `${VCT_A} ${VCT_B} OPTN DOWN 4 OPTN 4 RP EQ`, { manual: '(0.6, 0.8)', core: true }),
      t('VctA•VctC, mismatched dimensions', 'MENU 5 1 2 1 EQ 2 EQ AC OPTN 1 3 3 2 EQ NEG 1 EQ 2 EQ AC OPTN 3 OPTN DOWN 2 OPTN 5 EQ', { manual: 'Dimension ERROR' }),
      t('Angle(VctA, VctB), Fix 3 (p.29)', `${fix(3)} ${VCT_A} ${VCT_B} OPTN DOWN 3 OPTN 3 SHIFT RP OPTN 4 RP EQ`, { manual: '10.305', core: true }),
    ],
  },
  {
    id: 'M', title: 'Statistics mode', start: { text: 'Default setup; each test re-enters Statistics', keys: '' },
    tests: [
      t('Select Type menu (p.20)', 'MENU 6', { core: true }),
      t('Select Type, page 2 (p.20)', 'MENU 6 DOWN'),
      t('Editor with Freq (p.22 Ex 2)', FREQ_DATA, { core: true }),
      t('Mean with Freq (p.22 Ex 2)', `${FREQ_DATA} AC OPTN DOWN 2 1 EQ`, { manual: '3', core: true }),
      t('x ▸t (p.23 Ex 5)', `${FREQ_DATA} AC 2 OPTN DOWN 4 4 EQ`, { manual: '−0.8660254038', core: true }),
      t('P(Ans) (p.23 Ex 5)', `${FREQ_DATA} AC 2 OPTN DOWN 4 4 EQ OPTN DOWN 4 1 ANS RP EQ`, { manual: '0.19324', core: true }),
      t('1-Variable Calc list (p.21)', `${FREQ_DATA} OPTN 3`, { core: true }),
      t('… scrolled 4 lines', `${FREQ_DATA} OPTN 3 DOWN DOWN DOWN DOWN`),
      t('… scrolled to the end', `${FREQ_DATA} OPTN 3 DOWN DOWN DOWN DOWN DOWN DOWN DOWN DOWN DOWN`),
      t('Q1 with an odd count (1…7)', `${statFreq(0)} MENU 6 1 1 EQ 2 EQ 3 EQ 4 EQ 5 EQ 6 EQ 7 EQ AC OPTN DOWN 3 2 EQ`, { core: true, note: 'Distinguishes the quartile method: 2 or 2.5' }),
      t('Q3 with an odd count (1…7)', `${statFreq(0)} MENU 6 1 1 EQ 2 EQ 3 EQ 4 EQ 5 EQ 6 EQ 7 EQ AC OPTN DOWN 3 4 EQ`, { core: true }),
      t('Median with an even count (1…6)', `${statFreq(0)} MENU 6 1 1 EQ 2 EQ 3 EQ 4 EQ 5 EQ 6 EQ AC OPTN DOWN 3 3 EQ`),
      t('Logarithmic r (p.22 Ex 3)', `${LOG_DATA} AC OPTN DOWN 4 3 EQ`, { manual: '0.998 (Fix 3)', core: true }),
      t('Logarithmic a (p.22 Ex 3)', `${LOG_DATA} AC OPTN DOWN 4 1 EQ`, { manual: '−3857.984 (Fix 3)' }),
      t('Logarithmic b (p.22 Ex 3)', `${LOG_DATA} AC OPTN DOWN 4 2 EQ`, { manual: '2357.532 (Fix 3)' }),
      t('ŷ for x=160 (p.22 Ex 4)', `${LOG_DATA} AC 1 6 0 OPTN DOWN 4 5 EQ`, { manual: '8106.898 (Fix 3)', core: true }),
      t('Regression Calc list (p.21 Ex 1)', 'MENU 6 4 1 7 0 EQ 1 7 3 EQ 1 7 9 EQ DOWN RIGHT 6 6 EQ 6 8 EQ 7 5 EQ OPTN 4', { manual: 'a=−852.1627746, b=178.6897969, r=0.9919863213', core: true }),
      t('Linear regression list', `${LIN_DATA} OPTN 4`, { core: true }),
      t('Linear x̂ for y=10', `${LIN_DATA} AC 1 0 OPTN DOWN 4 4 EQ`),
      t('Quadratic regression list', `${QUAD_DATA} OPTN 4`, { core: true }),
      t('Quadratic x̂₁ for y=7', `${QUAD_DATA} AC 7 OPTN DOWN 4 4 EQ`),
      t('Quadratic x̂₂ for y=7', `${QUAD_DATA} AC 7 OPTN DOWN 4 5 EQ`),
      t('e-exponential regression list', 'MENU 6 DOWN 1 1 EQ 2 EQ 3 EQ DOWN RIGHT 2 DOT 7 EQ 7 DOT 4 EQ 2 0 DOT 1 EQ OPTN 4'),
      t('ab-exponential regression list', 'MENU 6 DOWN 2 1 EQ 2 EQ 3 EQ DOWN RIGHT 2 DOT 7 EQ 7 DOT 4 EQ 2 0 DOT 1 EQ OPTN 4'),
      t('Power regression list', 'MENU 6 DOWN 3 1 EQ 2 EQ 3 EQ DOWN RIGHT 2 EQ 8 EQ 1 8 EQ OPTN 4'),
      t('Inverse regression list', 'MENU 6 DOWN 4 1 EQ 2 EQ 4 EQ DOWN RIGHT 3 EQ 2 EQ 1 DOT 5 EQ OPTN 4'),
      t('2-Variable Calc list', `${LIN_DATA} OPTN 3`, { core: true }),
      t('Σxy', `${LIN_DATA} AC OPTN DOWN 1 5 EQ`),
      t('Statistics OPTN, page 2 (paired)', `${LIN_DATA} AC OPTN DOWN`),
      t('Editor: Insert Row (p.21)', 'MENU 6 1 1 EQ 2 EQ 3 EQ UP UP OPTN 2 1'),
      t('Editor: DEL deletes a row (p.21)', 'MENU 6 1 1 EQ 2 EQ 3 EQ UP UP DEL'),
    ],
  },
  {
    id: 'N', title: 'Distribution mode', start: { text: 'Default setup; each test re-enters Distribution', keys: '' },
    tests: [
      t('Type menu (p.31)', 'MENU 7', { core: true }),
      t('Type menu, page 2 (p.31)', 'MENU 7 DOWN'),
      t('Normal PD input screen (p.32)', 'MENU 7 1', { core: true }),
      t('Normal PD x=36, σ=2, μ=35 (p.32)', 'MENU 7 1 3 6 EQ 2 EQ 3 5 EQ EQ', { manual: '0.1760326634', core: true }),
      t('Normal CD, −1 to 1', 'MENU 7 2 NEG 1 EQ 1 EQ 1 EQ 0 EQ EQ', { core: true }),
      t('Normal CD, −10⁹⁹ to 0', 'MENU 7 2 NEG 1 EXP 9 9 EQ 0 EQ 1 EQ 0 EQ EQ'),
      t('Inverse Normal, Area 0.95', 'MENU 7 3 0 DOT 9 5 EQ 1 EQ 0 EQ EQ', { core: true }),
      t('Inverse Normal, Area 0.25, σ=15, μ=100', 'MENU 7 3 0 DOT 2 5 EQ 1 5 EQ 1 0 0 EQ EQ'),
      t('List/Variable dialog (p.31)', 'MENU 7 4'),
      t('Binomial PD, x=3, N=10, p=0.5', 'MENU 7 4 2 3 EQ 1 0 EQ 0 DOT 5 EQ EQ', { core: true }),
      t('Binomial CD, x=3, N=10, p=0.5', 'MENU 7 DOWN 1 2 3 EQ 1 0 EQ 0 DOT 5 EQ EQ', { core: true }),
      t('Poisson PD, x=2, λ=3', 'MENU 7 DOWN 2 2 2 EQ 3 EQ EQ', { core: true }),
      t('Poisson CD, x=2, λ=3', 'MENU 7 DOWN 3 2 2 EQ 3 EQ EQ'),
      t('Binomial PD list (p.32)', 'MENU 7 4 1 1 0 EQ 1 1 EQ 1 2 EQ 1 3 EQ EQ 1 5 EQ 0 DOT 6 EQ EQ', { manual: '0.1859, 0.1267, 0.0633, 0.0219', core: true }),
      t('σ = 0', 'MENU 7 1 0 EQ 0 EQ 0 EQ EQ'),
      t('p > 1', 'MENU 7 4 2 1 EQ 2 EQ 2 EQ EQ'),
      t('Result stored in Ans (p.31)', 'MENU 7 1 3 6 EQ 2 EQ 3 5 EQ EQ MENU 1 ANS EQ', { manual: '0.1760326634' }),
    ],
  },
  {
    id: 'O', title: 'Table mode', start: { text: 'Default setup (Table: f(x),g(x))', keys: '' },
    tests: [
      t('Number table (p.27)', `${TABLE_FG} EQ`, { manual: '−1: 1.5, 0.5 / −0.5: 0.75, −0.25 / 0: 0.5, −0.5 / 0.5: 0.75, −0.25', core: true }),
      t('Table Range screen (p.27)', TABLE_FG, { core: true }),
      t('Scrolling the table', `${TABLE_FG} EQ DOWN DOWN DOWN DOWN`),
      t('Editing an x cell (p.27 tip)', `${TABLE_FG} EQ 3 EQ`),
      t('f(x) only', `${table(0)} MENU 9 AC ALPHA RP SQR EQ 1 EQ 5 EQ 1 EQ EQ`, { core: true }),
      t('46 rows → Range ERROR (p.28)', `${table(0)} MENU 9 AC ALPHA RP EQ 1 EQ 4 6 EQ 1 EQ EQ`, { manual: 'Range ERROR' }),
      t('ERROR in a cell (1/x at 0)', `${table(0)} MENU 9 AC 1 FRAC ALPHA RP EQ NEG 1 EQ 1 EQ 1 EQ EQ`),
      t('sin x in Radian', `${table(0)} ${angle(2)} MENU 9 AC SIN ALPHA RP RP EQ 0 EQ SHIFT EXP EQ SHIFT EXP DIV 4 EQ EQ`),
    ],
  },
  {
    id: 'P', title: 'Equation/Func mode', start: { text: 'Default setup; each test re-enters Equation/Func (MENU, then the (−) key for A)', keys: '' },
    tests: [
      t('Coefficient editor (p.25)', 'MENU NEG 1 2 1 EQ 2 EQ 3 EQ 2 EQ 3 EQ 4', { core: true }),
      t('x+2y=3, 2x+3y=4: x (p.25)', 'MENU NEG 1 2 1 EQ 2 EQ 3 EQ 2 EQ 3 EQ 4 EQ EQ', { manual: 'x=−1', core: true }),
      t('… y (p.25)', 'MENU NEG 1 2 1 EQ 2 EQ 3 EQ 2 EQ 3 EQ 4 EQ EQ EQ', { manual: 'y=2' }),
      t('Three unknowns: x', 'MENU NEG 1 3 1 EQ 1 EQ 1 EQ 6 EQ 2 EQ NEG 1 EQ 1 EQ 3 EQ 1 EQ 2 EQ NEG 1 EQ 2 EQ EQ'),
      t('Three unknowns: z', 'MENU NEG 1 3 1 EQ 1 EQ 1 EQ 6 EQ 2 EQ NEG 1 EQ 1 EQ 3 EQ 1 EQ 2 EQ NEG 1 EQ 2 EQ EQ EQ EQ'),
      t('Fraction solution: x', 'MENU NEG 1 2 2 EQ 3 EQ 1 EQ 4 EQ NEG 1 EQ 5 EQ EQ', { core: true }),
      t('Fraction solution: y', 'MENU NEG 1 2 2 EQ 3 EQ 1 EQ 4 EQ NEG 1 EQ 5 EQ EQ EQ'),
      t('No Solution (p.25)', 'MENU NEG 1 2 1 EQ 1 EQ 1 EQ 2 EQ 2 EQ 3 EQ EQ', { core: true }),
      t('Infinite Solution (p.25)', 'MENU NEG 1 2 1 EQ 1 EQ 1 EQ 2 EQ 2 EQ 2 EQ EQ'),
      t('x²+2x−2=0: x₁ (p.25)', 'MENU NEG 2 2 1 EQ 2 EQ NEG 2 EQ EQ', { manual: '−1+√3', core: true }),
      t('… x₂ (p.25)', 'MENU NEG 2 2 1 EQ 2 EQ NEG 2 EQ EQ DOWN', { manual: '−1−√3' }),
      t('… vertex x (p.25)', 'MENU NEG 2 2 1 EQ 2 EQ NEG 2 EQ EQ DOWN DOWN', { manual: '−1', core: true }),
      t('… vertex y (p.25)', 'MENU NEG 2 2 1 EQ 2 EQ NEG 2 EQ EQ DOWN DOWN DOWN', { manual: '−3' }),
      t('2x²+x−3=0: x₁ (p.24)', 'MENU NEG 2 2 2 EQ 1 EQ NEG 3 EQ EQ'),
      t('2x²+x−3=0: x₂', 'MENU NEG 2 2 2 EQ 1 EQ NEG 3 EQ EQ DOWN'),
      t('x²+1=0: x₁', 'MENU NEG 2 2 1 EQ 0 EQ 1 EQ EQ', { core: true }),
      t('x²+1=0: x₂', 'MENU NEG 2 2 1 EQ 0 EQ 1 EQ EQ DOWN'),
      t('x³−6x²+11x−6: x₁ (root order)', 'MENU NEG 2 3 1 EQ NEG 6 EQ 1 1 EQ NEG 6 EQ EQ', { core: true }),
      t('… x₂', 'MENU NEG 2 3 1 EQ NEG 6 EQ 1 1 EQ NEG 6 EQ EQ DOWN'),
      t('… x₃', 'MENU NEG 2 3 1 EQ NEG 6 EQ 1 1 EQ NEG 6 EQ EQ DOWN DOWN'),
      t('x³−1: x₂ (complex pair)', 'MENU NEG 2 3 1 EQ 0 EQ 0 EQ NEG 1 EQ EQ DOWN', { core: true }),
      t('x³−3x+1: x₁ (irrational)', 'MENU NEG 2 3 1 EQ 0 EQ NEG 3 EQ 1 EQ EQ', { core: true }),
      t('x⁴−5x²+4: x₁', 'MENU NEG 2 4 1 EQ 0 EQ NEG 5 EQ 0 EQ 4 EQ EQ', { core: true }),
      t('x⁴−5x²+4: x₄', 'MENU NEG 2 4 1 EQ 0 EQ NEG 5 EQ 0 EQ 4 EQ EQ DOWN DOWN DOWN'),
      t('x⁴+1: x₁', 'MENU NEG 2 4 1 EQ 0 EQ 0 EQ 0 EQ 1 EQ EQ'),
      t('Double root x²−2x+1', 'MENU NEG 2 2 1 EQ NEG 2 EQ 1 EQ EQ', { core: true }),
      t('Leading coefficient 0', 'MENU NEG 2 2 0 EQ 1 EQ 1 EQ EQ'),
      t('Equation/Func complex Off: x²+1=0 (p.7)', `${eqComplex(0)} MENU NEG 2 2 1 EQ 0 EQ 1 EQ EQ`, { core: true }),
    ],
  },
  {
    id: 'Q', title: 'Inequality mode', start: { text: 'Default setup; each test re-enters Inequality (MENU, then the °’” key for B)', keys: '' },
    tests: [
      t('Degree dialog (p.29)', 'MENU DMS', { core: true }),
      t('Inequality type menu (p.29)', 'MENU DMS 3'),
      t('3x³+3x²−x>0 (p.30)', 'MENU DMS 3 1 3 EQ 3 EQ NEG 1 EQ 0 EQ EQ', { manual: '(−3−√21)/6<x<0, (−3+√21)/6<x', core: true }),
      t('x²+2x−3<0 (p.29)', 'MENU DMS 2 2 1 EQ 2 EQ NEG 3 EQ EQ', { core: true }),
      t('x² ≥ 0 (p.30)', 'MENU DMS 2 3 1 EQ 0 EQ 0 EQ EQ', { manual: 'All Real Numbers' }),
      t('x² < 0 (p.30)', 'MENU DMS 2 2 1 EQ 0 EQ 0 EQ EQ', { manual: 'No Solution' }),
      t('x²−2x+1 ≤ 0', 'MENU DMS 2 4 1 EQ NEG 2 EQ 1 EQ EQ', { core: true }),
      t('x²−2x+1 > 0', 'MENU DMS 2 1 1 EQ NEG 2 EQ 1 EQ EQ', { core: true }),
      t('x²−2 > 0', 'MENU DMS 2 1 1 EQ 0 EQ NEG 2 EQ EQ'),
      t('x⁴−5x²+4 ≤ 0', 'MENU DMS 4 4 1 EQ 0 EQ NEG 5 EQ 0 EQ 4 EQ EQ'),
      t('−x²+4 > 0', 'MENU DMS 2 1 NEG 1 EQ 0 EQ 4 EQ EQ'),
      t('LineI/LineO display (p.30 note)', `${io(3)} MENU DMS 3 1 3 EQ 3 EQ NEG 1 EQ 0 EQ EQ`, { manual: 'a<x<b, c<x with a=−1.263762616, b=0, c=0.2637626158', core: true }),
    ],
  },
  {
    id: 'R', title: 'Ratio mode', start: { text: 'Default setup; each test re-enters Ratio (MENU, then the x⁻¹ key for C)', keys: '' },
    tests: [
      t('Type menu (p.30)', 'MENU INV'),
      t('Editor screen (p.30)', 'MENU INV 1 1 EQ 2 EQ 1 0', { core: true }),
      t('1:2 = X:10 (p.30)', 'MENU INV 1 1 EQ 2 EQ 1 0 EQ EQ', { manual: 'X=5', core: true }),
      t('3:8 = X:12 (p.30)', 'MENU INV 1 3 EQ 8 EQ 1 2 EQ EQ'),
      t('2:3 = 4:X', 'MENU INV 2 2 EQ 3 EQ 4 EQ EQ'),
      t('Zero coefficient (p.30)', 'MENU INV 1 0 EQ 2 EQ 3 EQ EQ', { manual: 'Math ERROR' }),
      t('1.5:2.5 = X:4', 'MENU INV 1 1 DOT 5 EQ 2 DOT 5 EQ 4 EQ EQ', { core: true }),
    ],
  },
  {
    id: 'S', title: 'Spreadsheet mode', start: { text: 'Default setup; each test re-enters Spreadsheet', keys: '' },
    tests: [
      t('Constants in A1–A3 (p.33 Ex 1)', SHEET, { core: true }),
      t('Formula =A1+7 in B1 (p.33 Ex 1)', SHEET_B1, { manual: 'B1 = 42', core: true }),
      t('Grab: =A2+7 in B2 (p.34 Ex 2)', `${SHEET_B1} ALPHA CALC OPTN 2 LEFT EQ ADD 7 EQ`, { manual: 'B2 = 49' }),
      t('=Sum(A1:A3) in A4 (p.35 Ex 3)', `${SHEET_B1} LEFT DOWN DOWN ALPHA CALC OPTN DOWN 4 ALPHA NEG 1 ALPHA INT ALPHA NEG 3 RP EQ`, { manual: 'A4 = 126', core: true }),
      t('Formula shown in the edit box', `${SHEET_B1} LEFT DOWN DOWN ALPHA CALC OPTN DOWN 4 ALPHA NEG 1 ALPHA INT ALPHA NEG 3 RP EQ UP`),
      t('Fill Formula B1:B3 =2A1−3 (p.36 Ex 4)', `${SHEET_B1} UP OPTN 1 2 ALPHA NEG 1 SUB 3 EQ RIGHT RIGHT RIGHT RIGHT RIGHT RIGHT DEL 3 EQ EQ`, { manual: 'B1–B3 = 67, 81, 95', core: true }),
      t('Fill Value C1:C3 = B1×3 (p.36 Ex 5)', `${SHEET_B1} UP OPTN 1 2 ALPHA NEG 1 SUB 3 EQ RIGHT RIGHT RIGHT RIGHT RIGHT RIGHT DEL 3 EQ EQ RIGHT OPTN 2 ALPHA DMS 1 MUL 3 EQ RIGHT RIGHT RIGHT RIGHT RIGHT RIGHT DEL 3 EQ EQ`, { manual: 'C1–C3 = 201, 243, 285' }),
      t('Copy & Paste moves relative references (p.34)', `${SHEET_B1} UP OPTN DOWN 2 DOWN DOWN EQ`, { manual: 'B3: =A3+7', core: true }),
      t('Cut & Paste keeps references (p.35)', `${SHEET_B1} UP OPTN DOWN 1 RIGHT EQ`),
      t('Absolute reference $A$1 (p.34)', `${SHEET} UP UP UP RIGHT ALPHA CALC OPTN 1 ALPHA NEG OPTN 1 1 ADD 7 EQ UP OPTN DOWN 2 DOWN EQ AC`),
      t('Circular reference (p.39)', 'MENU 8 ALPHA CALC ALPHA NEG 1 EQ', { manual: 'Circular ERROR', core: true }),
      t('=Mean(A1:A3)', `${SHEET} ALPHA CALC OPTN DOWN 3 ALPHA NEG 1 ALPHA INT ALPHA NEG 3 RP EQ`),
      t('Edit Cell (p.34)', `${SHEET_B1} UP OPTN 3`),
      t('Free Space (p.33)', `${SHEET} OPTN 4`),
      t('Show Cell: Value', `${showCellValue()} ${SHEET_B1} UP`),
    ],
  },
  {
    id: 'T', title: 'Menus and screens', start: { text: 'Calculate mode, default setup', keys: '' },
    tests: [
      t('Main menu (p.4)', 'AC MENU', { core: true }),
      t('Main menu, third row', 'AC MENU DOWN DOWN'),
      t('OPTN in Calculate', 'AC OPTN', { core: true }),
      t('Hyperbolic Func menu', 'AC OPTN 1'),
      t('Angle Unit menu', 'AC OPTN 2'),
      t('Engineer Symbol menu (p.12)', 'AC OPTN 3'),
      t('CONST categories (p.37)', 'AC SHIFT 7', { core: true }),
      t('CONST categories, page 2', 'AC SHIFT 7 DOWN'),
      t('Universal constants (p.37)', 'AC SHIFT 7 1', { core: true }),
      t('Atomic&Nuclear constants', 'AC SHIFT 7 3'),
      t('CONV categories (p.37)', 'AC SHIFT 8', { core: true }),
      t('Length conversions (p.37)', 'AC SHIFT 8 1'),
      t('RESET menu', 'AC SHIFT 9'),
      t('Initialize All confirmation', 'AC SHIFT 9 3'),
      t('Error screen (p.37)', 'AC 1 DIV 0 EQ', { core: true }),
      t('◀ after an error goes to the input (p.37)', 'AC 1 DIV 0 EQ LEFT'),
      t('QR code (p.17)', 'AC 1 ADD 1 EQ SHIFT OPTN', { note: 'Known difference: QR codes are not generated' }),
      t('Overwrite mode in LineI/LineO (p.10)', `AC ${io(3)} 1 2 3 LEFT LEFT SHIFT DEL 9`),
    ],
  },
  {
    id: 'U', title: 'Constants and conversions', start: { text: 'Calculate mode, default setup', keys: '' },
    tests: [
      t('c₀ (p.37)', 'AC SHIFT 7 1 3 EQ', { manual: '299792458', core: true }),
      t('h', 'AC SHIFT 7 1 1 EQ', { core: true }),
      t('G', 'AC SHIFT 7 1 7 EQ'),
      t('e (elementary charge)', 'AC SHIFT 7 2 3 EQ'),
      t('mₑ', 'AC SHIFT 7 3 3 EQ'),
      t('R∞ (item C)', 'AC SHIFT 7 3 INV EQ'),
      t('μμ (item M)', 'AC SHIFT 7 3 MPLUS EQ'),
      t('mτ (item x)', 'AC SHIFT 7 3 X EQ'),
      t('N_A', 'AC SHIFT 7 4 3 EQ'),
      t('g', 'AC SHIFT 7 DOWN 1 1 EQ'),
      t('t', 'AC SHIFT 7 DOWN 2 1 EQ', { core: true }),
      t('2×c₀', 'AC 2 SHIFT 7 1 3 EQ'),
      t('5 cm▸in in MathI/MathO', 'AC 5 SHIFT 8 1 2 EQ', { core: true }),
      t('1 in▸cm', 'AC 1 SHIFT 8 1 1 EQ'),
      t('1 pc▸km (item B)', 'AC 1 SHIFT 8 1 DMS EQ', { core: true }),
      t('1 acre▸m²', 'AC 1 SHIFT 8 2 1 EQ', { core: true }),
      t('1 gal(US)▸L', 'AC 1 SHIFT 8 3 1 EQ'),
      t('1 lb▸kg', 'AC 1 SHIFT 8 4 3 EQ', { core: true }),
      t('100 atm▸Pa', 'AC 1 0 0 SHIFT 8 DOWN 1 1 EQ'),
      t('1 mmHg▸Pa', 'AC 1 SHIFT 8 DOWN 1 3 EQ', { core: true }),
      t('1 lbf/in²▸kPa', 'AC 1 SHIFT 8 DOWN 1 7 EQ'),
      t('1 J▸cal (15 °C calorie, p.37)', 'AC 1 SHIFT 8 DOWN 2 3 EQ', { core: true }),
      t('1 hp▸kW', 'AC 1 SHIFT 8 DOWN 3 1 EQ', { core: true }),
      t('100 °F▸°C', 'AC 1 0 0 SHIFT 8 DOWN 4 1 EQ'),
      t('−40 °C▸°F', 'AC NEG 4 0 SHIFT 8 DOWN 4 2 EQ'),
      t('5 cm▸in in LineI/LineO (p.37)', `AC ${io(3)} 5 SHIFT 8 1 2 EQ`, { manual: '1.968503937', core: true }),
      // ATOMIC (SHIFT 4), fx-991CE X only
      t('ATOMIC menu', 'AC SHIFT 4', { core: true }),
      t('Periodic table, first screen', 'AC SHIFT 4 1', { core: true }),
      t('Periodic table: ▼▼▼▶▶ and = inserts AtWt', 'AC SHIFT 4 1 DOWN DOWN DOWN RIGHT RIGHT EQ'),
      t('AtWt 21 (Sc)', 'AC SHIFT 4 2 2 1 EQ', { manual: '44,955908', core: true }),
      t('AtWt 43 (Tc, no stable isotope)', 'AC SHIFT 4 2 4 3 EQ'),
      t('AtWt 1 + AtWt 8 × 2', 'AC SHIFT 4 2 1 ADD SHIFT 4 2 8 MUL 2 EQ'),
      t('AtWt 119', 'AC SHIFT 4 2 1 1 9 EQ'),
      t('ATOMIC in Base-N', 'MENU 3 SHIFT 4'),
      t('Periodic table: lanthanoid cell (▼×5 ▶▶)', 'AC SHIFT 4 1 DOWN DOWN DOWN DOWN DOWN RIGHT RIGHT'),
      t('Periodic table: ▼▼ from the lanthanoid cell', 'AC SHIFT 4 1 DOWN DOWN DOWN DOWN DOWN RIGHT RIGHT DOWN DOWN'),
      t('AtWt 61 (Pm)', 'AC SHIFT 4 2 6 1 EQ'),
      t('AtWt 84 (Po)', 'AC SHIFT 4 2 8 4 EQ'),
      t('AtWt 103 (Lr)', 'AC SHIFT 4 2 1 0 3 EQ'),
      t('AtWt 118 (Og)', 'AC SHIFT 4 2 1 1 8 EQ'),
      t('AtWt 0', 'AC SHIFT 4 2 0 EQ'),
    ],
  },
];

/** Flat list with ids like "A01". */
export function allCases() {
  return SECTIONS.flatMap((s) => s.tests.map((tc, i) => ({
    ...tc,
    section: s.id,
    id: `${s.id}${String(i + 1).padStart(2, '0')}`,
    runKeys: `${s.start.keys} ${tc.keys}`.trim(),
  })));
}
